Backend import for 'as-a-module' use
ufal/whisper_streaming pull request #10
Opened 2023-09-06 14:13 UTC by Luca-Pozzi

With reference to issue #9, the present PR implements a `import_backed` method in `ASRBase`. The method is then appropriately overridden both in `WhisperTimestampedASR` and `FasterWhisperASR` to import the required libraries.

To make the use more flexible, I have also exposed the `output` arg in `OnlineASRProcessor`. It receives a file-like object, so one could pass:
- `sys.stderr` (as before) which in most cases will result into printing to terminal
- a file handler (`open("/path/to/file.txt", "a")`) to log the output to a text file
- `open(os.devnull, "w")`, to send the output to `/dev/null`, i.e. to discard it

2023-10-26 07:32 UTC, Gldkslfmsd requested changes
I forgot to "submit review"

2023-10-30 23:41 UTC, lrq3000 commented
@Luca-Pozzi Great work! Do you plan on finishing this PR? I would really like to use whisper_online as a module, being unable to greatly limits composability into more end user facing apps.

2023-10-31 08:57 UTC, Luca-Pozzi commented
@lrq3000 It is really a minor contribution, but thank you!
I plan to finish the PR by this week

2023-11-03 10:40 UTC, Luca-Pozzi commented
@Gldkslfmsd I have edited the PR as per your suggestions!
Thank you very much, and sorry if it took so long on my side.

2023-11-06 15:28 UTC, Gldkslfmsd commented
Thanks! No worries for late. 
I'm now busy until 25.11.2023, at least, I hope I'll look on this later.

2023-11-28 11:17 UTC, merged

2023-11-28 14:07 UTC, lrq3000 commented
Thank you both for your great work on this! :D

2023-12-08 06:12 UTC, umaryasin33 commented
How to use this to allow multiple clients to connect when you host a whisper transcription server?

2023-12-08 09:19 UTC, Gldkslfmsd commented
> How to use this to allow multiple clients to connect when you host a server or create an API for live transcription?

I don't know, it's a topic that requires a separate issue. 
But first, there must be a Whisper backend that enables batching -- more inputs processing at once.
If there's not, then use one GPU with one server for one client.

2023-12-08 11:06 UTC, umaryasin33 commented
> > How to use this to allow multiple clients to connect when you host a server or create an API for live transcription?
> 
> I don't know, it's a topic that requires a separate issue. But first, there must be a Whisper backend that enables batching -- more inputs processing at once. If there's not, then use one GPU with one server for one client.

Thank you. Using one GPU for each client is a tall ask for me as there could be up to  a dozen clients active at a particular time for my use case.  I think there are a few backends which do support batched processing. e.g.  https://github.com/Blair-Johnson/batch-whisper
 If you have any references or you can point me to the parts where changes are needed to implement this. 
 Or is it alright if I create a new issue for this?