Add MLX Whisper Backend for Apple Silicon
ufal/whisper_streaming pull request #147
Opened 2024-12-19 10:39 UTC by QuentinFuxa

Hi, 

As indicated in my [previous pull request](https://github.com/ufal/whisper_streaming/pull/146#issuecomment-2553357043), this PR concerns exclusively the mlx-whisper backend:

The Whisper MLX backend is optimized specifically for Apple Silicon. It uses the mlx-whisper library, which leverages the native performance capabilities of Apple hardware for faster transcription without requiring a dedicated GPU.

**Key Changes**

- MLXWhisper Backend: Added MLXWhisper as a new class in the backend options.
  - Automatically translates model names (e.g., large-v2) to MLX-compatible Hugging Face paths (e.g., whisper-large-v2-mlx).
  - No change to the --model parameter in the project CLI, model "translation" is done in the background.

- Readme has been updated with information & how to install (`pip install mlx-whisper`)

**Testing**
- The implementation has been tested on Apple M1. It works faster than faster whisper.

**Usage Example**

`python whisper_streaming.py --model "large-v3-turbo" --backend "mlx-whisper"`

The MLXWhisper class translates the model name to the Hugging Face path mlx-community/whisper-large-v3-turbo and loads the model efficiently.

Let me know if you have any questions or need further clarifications!

Best regards,
Quentin

2025-01-05 10:07 UTC, fraschm1998 commented
> OK, thanks. I'm changing my mind. I can't review and test this code but I'd like to ask any volunteer to do so and let me know. Then I'd merge it.

Can confirm it works. Tested on M4 Pro MBPro.

2025-01-06 08:19 UTC, Gldkslfmsd requested changes

2025-01-06 08:19 UTC, Gldkslfmsd commented on whisper_online.py
> +        mlx_model_path = model_mapping.get(model_name)
The model should be loaded within this method, and not during the first use of transcribe, that would make it slower. 

Please run this here: https://github.com/ml-explore/mlx-examples/blob/25ec2d8c4496be68acf7e0c9ea1ae4269e1a2a19/whisper/mlx_whisper/transcribe.py#L55

This get_model method loads the model into the static class, which is kind of global variable. It's not nice, there can't be two different models at once, someone could need it when using whisper-streaming as a module. But I understand that changing this is difficult, so let's at least point it in a comment.

2025-01-06 08:21 UTC, Gldkslfmsd requested changes

2025-01-06 08:21 UTC, Gldkslfmsd commented on whisper_online.py
> +        mlx_model_path = model_mapping.get(model_name)
(I mean this comment for line 190, not 221)

2025-01-07 08:07 UTC, QuentinFuxa commented on whisper_online.py
> +        mlx_model_path = model_mapping.get(model_name)
Good point!

> But I understand that changing this is difficult, so let's at least point it in a comment

Without directly submitting a PR to modify the get_model method in mlx-whisper to load the model into a local variable instead of a static class, an alternative would be to copy and adapt the mlx-whisper transcribe.transcribe method directly within whisper_streaming. 
The required changes would likely involve modifying just a few lines, so the limitation is more about keeping the MLXWhisper class tiny and maintaining consistency with the original library. 

I have made a comment to explain possible limitations

2025-01-07 12:26 UTC, merged